const std::unordered_map<std::string, std::string> REFLECTORWIRINGS = {
        {"A","EJMZALYXVBWFCRQUONTSPIKHGD"}, 
        {"B","YRUHQSLDPXNGOKMIEBFZCWVJAT"},
        {"C","FVPJIAOYEDRZXWGCTKUQSBNMHL"},
        {"BTHIN","ENKQAUYWJICOPBLMDXZVFTHRGS"},
        {"CTHIN","RDOBJNTKVEHMLFCWZAXGYIPSUQ"},
        {"BETA","LEYJVCNIXWPBQMDRTAKZGFUHOS"},
        {"GAMMA","FSOKANUERHMBTIYCWLQPZXVGJD"},
        {"ETW","ABCDEFGHIJKLMNOPQRSTUVWXYZ"}
};